
#ifndef GAMEPROJECT_MONSTER_ATTRIBUTES_H
#define GAMEPROJECT_MONSTER_ATTRIBUTES_H


#define START_HP 1000

#define DEFAULT_MIN_RANGE 100
#define DEFAULT_MAX_RANGE 200

#define DEFAULT_DEFENCE 50
#define DEFAULT_DODGE 4

#define INCREASE_DEFAULT_MIN_RANGE 10
#define INCREASE_DEFAULT_MAX_RANGE 10

#define INCREASE_DEFAULT_DEFENCE 30
#define INCREASE_DEFAULT_DODGE 2

#define DRAGON_MIN_RANGE 150
#define DRAGON_MAX_RANGE 250

#define INCREASE_DRAGON_MIN_RANGE 20
#define INCREASE_DRAGON_MAX_RANGE 20

#define EXOSKELETON_DEFENCE 120
#define INCREASE_EXOSKELETON_DEFENCE 20

#define SPIRIT_DODGE 6
#define INCREASE_SPIRIT_DODGE 3


#endif //GAMEPROJECT_MONSTER_ATTRIBUTES_H