#ifndef GAMEPROJECT_MONSTER_ATTRIBUTES_H
#define GAMEPROJECT_MONSTER_ATTRIBUTES_H

#define START_HP 1000

#define DEFAULT_MIN_RANGE 400
#define DEFAULT_MAX_RANGE 500

#define DEFAULT_DEFENCE 100

#define DEFAULT_DODGE 10

#define INCREASE_DEFAULT_MIN_RANGE 30
#define INCREASE_DEFAULT_MAX_RANGE 30

#define INCREASE_DEFAULT_DEFENCE 20

#define INCREASE_DEFAULT_DODGE 5

#define DRAGON_MIN_RANGE 500
#define DRAGON_MAX_RANGE 600

#define INCREASE_DRAGON_MIN_RANGE 50
#define INCREASE_DRAGON_MAX_RANGE 50

#define EXOSKELETON_DEFENCE 200

#define INCREASE_EXOSKELETON_DEFENCE 40

#define SPIRIT_DODGE 20

#define INCREASE_SPIRIT_DODGE 8

#endif //GAMEPROJECT_MONSTER_ATTRIBUTES_H
