#ifndef GAMEPROJECT_HERO_ATTRIBUTES_H
#define GAMEPROJECT_HERO_ATTRIBUTES_H

enum Attribute{Health, Mana, Experience, Money, Strength, Dexterity, Agility};

#define START_LEVEL 1
#define START_XP 0
#define START_HP 100
#define START_MP 100
#define START_MONEY 1000

#define DEFAULT_STRENGTH 50
#define DEFAULT_DEXTERITY 50
#define DEFAULT_AGILITY 50

#define INCREASE_DEFAULT_STRENGTH 10
#define INCREASE_DEFAULT_DEXTERITY 10
#define INCREASE_DEFAULT_AGILITY 10

#define WARRIOR_STRENGTH 70
#define WARRIOR_AGILITY 60

#define INCREASE_WARRIOR_STRENGTH 20
#define INCREASE_WARRIOR_AGILITY 20

#define SORCERER_DEXTERITY 80
#define SORCERER_AGILITY 60

#define INCREASE_SORCERER_DEXTERITY 30
#define INCREASE_SORCERER_AGILITY 20

#define PALADIN_STRENGTH 60
#define PALADIN_DEXTERITY 60

#define INCREASE_PALADIN_STRENGTH 15
#define INCREASE_PALADIN_DEXTERITY 15

#endif //GAMEPROJECT_HERO_ATTRIBUTES_H
