
#ifndef GAMEPROJECT_HERO_ATTRIBUTES_H
#define GAMEPROJECT_HERO_ATTRIBUTES_H

enum Attribute{Health, Mana, Strength, Dexterity, Agility};

#define START_LEVEL 1
#define START_XP 0
#define START_HP 1000
#define START_MP 1000
#define START_MONEY 1000

#define DEFAULT_STRENGTH 500
#define DEFAULT_DEXTERITY 500
#define DEFAULT_AGILITY 500

#define INCREASE_DEFAULT_STRENGTH 20
#define INCREASE_DEFAULT_DEXTERITY 20
#define INCREASE_DEFAULT_AGILITY 20

#define WARRIOR_STRENGTH 600
#define WARRIOR_AGILITY 600

#define INCREASE_WARRIOR_STRENGTH 40
#define INCREASE_WARRIOR_AGILITY 40

#define SORCERER_DEXTERITY 800
#define SORCERER_AGILITY 600

#define INCREASE_SORCERER_DEXTERITY 30
#define INCREASE_SORCERER_AGILITY 30

#define PALADIN_STRENGTH 750
#define PALADIN_DEXTERITY 750

#define INCREASE_PALADIN_STRENGTH 25
#define INCREASE_PALADIN_DEXTERITY 25

#endif //GAMEPROJECT_HERO_ATTRIBUTES_H
