
#ifndef GAMEPROJECT_HERO_ATTRIBUTES_H
#define GAMEPROJECT_HERO_ATTRIBUTES_H

enum Attribute{Health, Mana, Strength, Dexterity, Agility};

#define START_LEVEL 1
#define START_XP 0
#define START_HP 1000
#define START_MP 1000
#define START_MONEY 1000

#define DEFAULT_STRENGTH 100
#define DEFAULT_DEXTERITY 50
#define DEFAULT_AGILITY 5

#define INCREASE_DEFAULT_STRENGTH 50
#define INCREASE_DEFAULT_DEXTERITY 20
#define INCREASE_DEFAULT_AGILITY 2

#define WARRIOR_STRENGTH 200
#define WARRIOR_AGILITY 8

#define INCREASE_WARRIOR_STRENGTH 80
#define INCREASE_WARRIOR_AGILITY 4

#define SORCERER_DEXTERITY 100
#define SORCERER_AGILITY 10

#define INCREASE_SORCERER_DEXTERITY 60
#define INCREASE_SORCERER_AGILITY 5

#define PALADIN_STRENGTH 180
#define PALADIN_DEXTERITY 70

#define INCREASE_PALADIN_STRENGTH 30
#define INCREASE_PALADIN_DEXTERITY 25


#endif //GAMEPROJECT_HERO_ATTRIBUTES_H